Partial slash-commands rewrite
vare-team/whooves pull request #29
Opened 2022-09-02 17:12 UTC by Satan1c

2022-09-02 17:21 UTC, Dellyare commented on commands/context/about.js
> +	interaction.reply({embeds: [embed], ephemeral: true})
Кодстайл. Пробелы.

2022-09-02 17:21 UTC, Dellyare commented on commands/context/index.js
> +import {mapCommand} from "../../utils/functions.js";
Кодстайл. Пробелы.

2022-09-02 17:21 UTC, Dellyare commented on commands/context/index.js
> +import {mapCommand} from "../../utils/functions.js";
Так же кавычки

2022-09-02 17:22 UTC, Dellyare commented on commands/context/unshorten.js
> +import axios from "axios";
Кавычки

2022-09-02 17:22 UTC, Dellyare commented on commands/dev/index.js
> +import {mapCommand} from "../../utils/functions.js";
Пробелы

2022-09-02 17:23 UTC, Dellyare commented on commands/dev/publishcommand.js
> +import {commands} from '../index.js'
Пробелы

2022-09-02 17:23 UTC, Dellyare commented on commands/dev/publishcommand.js
Ентер лишний

2022-09-02 17:24 UTC, Dellyare commented on commands/dev/publishcommand.js
> +	fields = [];
wtf?

2022-09-02 17:24 UTC, Dellyare commented on commands/dev/publishcommand.js
> +	}else{
Пробелы

2022-09-02 17:25 UTC, Satan1c commented on commands/dev/publishcommand.js
> +	fields = [];
d.js просит не юзать депрекейтед метод addField, а вместо этого addFields

2022-09-02 17:25 UTC, Dellyare commented on commands/dev/publishcommand.js
> +	interaction.reply({ content: "done", ephemeral: true })
Embed не используется

2022-09-02 17:26 UTC, Dellyare commented on commands/dev/publishcommand.js
> +	let cmd = interaction.options.getString('команда') || "";
Кавычки

2022-09-02 17:26 UTC, Dellyare commented on commands/images/filter.js
> +import canvas from "canvas";
Кавычки

2022-09-02 17:27 UTC, Satan1c commented on commands/dev/publishcommand.js
> +	interaction.reply({ content: "done", ephemeral: true })
о, это я на время теста сделал, тк мне эмбед по кд прилетала ошибка о пустыхз полях, хотя по дебаггеру там все в норме

2022-09-02 17:27 UTC, Dellyare commented on commands/images/glitch.js
> +const {createCanvas, loadImage} = canvas;
Пробелы

2022-09-02 17:28 UTC, Dellyare commented on commands/images/index.js
> +import {mapCommand} from "../../utils/functions.js";
Пробелы и кавычки

2022-09-02 17:28 UTC, Dellyare commented on commands/images/petpet.js
> +import canvas from "canvas";
кавычки

2022-09-02 17:28 UTC, Dellyare commented on commands/images/petpet.js
> +const {createCanvas, loadImage} = canvas;
пробелы

2022-09-02 17:28 UTC, Dellyare commented on commands/images/roll.js
> +const {createCanvas, loadImage} = canvas;
пробелы

2022-09-02 18:07 UTC, SnakOleg commented
👍

2022-09-02 18:15 UTC, ArsArsArsArs commented
Мама, я в гитхаб логах

2022-09-02 18:18 UTC, flyare1337 commented
мама я в телевизоре

2022-09-02 18:19 UTC, MagM1go commented
мама я в

2022-09-02 18:23 UTC, TheMisterSenpai commented
это ясно, когда сдук в3?

2022-09-02 21:00 UTC, FedorLap2006 requested changes

2022-09-02 21:00 UTC, FedorLap2006 commented on events/onAutocomplete.js
> +	let cmd = commands[interaction.commandName.toLowerCase()]
```suggestion
	const cmd = commands[interaction.commandName.toLowerCase()]
```

2022-09-02 21:00 UTC, FedorLap2006 commented on events/onApplicationCommand.js
> +	let cmd = commands[interaction.commandName.toLowerCase()]
```suggestion
	const cmd = commands[interaction.commandName.toLowerCase()]
```

2022-10-09 11:12 UTC, MegaVasiliy007 approved these changes

2023-02-27 19:01 UTC, merged